name: My second Workflow

on: push
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Check Node version
        run: node -v

      - name: Download Dependencies
        run: npm install

      - name: list files
        run: ls 

  deploy-app:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: deploy
        run: echo "deployed"         